# Generated by Django 4.1.3 on 2022-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='DepartmentName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
