# Generated by Django 4.1.3 on 2022-11-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_departments_departmentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DateOfJoining',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PhotoFileName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
