# Generated by Django 4.1.3 on 2022-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_employee_dateofjoining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DateOfJoining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PhotoFileName',
            field=models.CharField(max_length=100),
        ),
    ]
